version: '3'

services: 
  front:
    image: nginx:1.15-alpine
    volumes: 
      - ./src/front:/usr/share/nginx/html
    ports: 
      - "5555:80"
    networks: 
      myapp_net:
        ipv4_address: 192.168.20.2

  php:
    image: php:7.3-alpine
    command: sh -c "cd /usr/src && php -S 0.0.0.0:8000"
    volumes:
      - ./src/apiPHP:/usr/src
    environment: 
      - CURRENCY=¥
    networks: 
      myapp_net:
        ipv4_address: 192.168.20.3

  dotnet:
    build:
      context: . 
      dockerfile: Dockerfile-net
    networks: 
      myapp_net:
        ipv4_address: 192.168.20.4

networks:
  myapp_net:
    ipam:
      config: 
        - subnet: 192.168.20.0/24