version: '3'

services: 
  wp:
    image: wordpress:5.2.1
    ports: 
      - "4444:80"
    environment: 
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    depends_on: 
      - db

  db:
    image: mysql:5
    environment: 
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
